from fastapi import FastAPI, HTTPException, Request, Depends
import os, json, sqlglot, asyncpg
import sqlglot.expressions as exp
from sqlalchemy.orm import Session
from dotenv import load_dotenv
from database import sessionLocal, User
load_dotenv()
from sqlalchemy.sql import text
app = FastAPI()
EXCLUDED_PATHS = ["/", "/docs", "/openapi.json"]
def get_db():
    db= sessionLocal()
    try:
        yield db
    finally:
        db.close()

@app.middleware("http")
async def middle(request: Request, call_next):
    if request.url.path in EXCLUDED_PATHS:
        await return call_next(request)
    token= request.headers.get("Authorization")
    if not token:
        raise HTTPException(status_code=401, detail="no auth token provided")
    payl= jwt.decode(token, os.getenv("JWT_SECRET"), algorithms=["HS256"])
    request.state.username, request.state.role, request.state.user_id = payl.get("username"), payl.get("role"), payl.get("user_id")
    resp = await call_next(request)
    return resp


@app.get("/")
def chek():
    return {"status": "Running"}

FORBIDDEN_COLUMNS = {"name", "phone", "email", "address", "aadhaar"}
def validate_sql_ast(sql: str, user_role: str):
    try:
        parsed = sqlglot.parse_one(sql)
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid SQL Syntax generated by SLM.")
    if not isinstance(parsed, exp.Select):
        raise HTTPException(status_code=403, detail="Security Risk: Only SELECT queries are permitted.")
    for column in parsed.find_all(exp.Column):
        if column.name.lower() in FORBIDDEN_COLUMNS:
            raise HTTPException(status_code=403,detail=f"Access Denied: Query requests protected PII column '{column.name}'.")
    tables = [table.name.lower() for table in parsed.find_all(exp.Table)]
    if "health_records" in tables and user_role != "ROLE_HEALTH_OFFICER":
        raise HTTPException(status_code=403, detail="not allowed")
    return True

@app.post("/query")
async def querydb(request: Request, db:Session=Depends(get_db)):
    username, role, user_id= await request.state.username, await request.state.role, await request.state.user_id
    user = db.query(User).filters(User.username==username, User.role==role, User.user_id==user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="no user found")
    body =await  request.json()
    sql_query = body["sql_query"]
    try:
        validate_sql_ast(sql_query, role)
        status = "ALLOWED"
    except HTTPException as e:
        # log it to database
        raise e
    conn = await asyncpg.connect(os.getenv("DATABASE_URL"))
    try:
        results = await conn.fetch(sql_query)
        data = [dict(record) for record in results]
    except Exception as db_err:
        await conn.close()
        raise HTTPException(status_code=500, detail=f"Database execution error: {str(db_err)}")
    await conn.close()
    # success log to db: TODO
    return {"status": "success", "row_count": len(data), "data": data}


